### ISSUE TITLE
Outline effect is bleeding into screen edges

### ISSUE THREAD

**Issue by XtroTheArctic** [Chishikii/URP-Render-Features#2]
Since you fixed the outline feature, I totally switched from Robinseibold's version to yours and it's mostly working fine. Thank you for everything.

But now I must report this screen edge problem.

Please see it on left, top, and right edges of this screenshot.
![image](https://github.com/Chishikii/URP-Render-Features/assets/6631429/cdf2f271-0a53-4dcc-8e22-f0ad51a5dba4)

Here is the texture from frame debugger. It's not the same frame from the above screenshot but the outline still bleeds into the screen edges.

![image](https://github.com/Chishikii/URP-Render-Features/assets/6631429/bf8b60e4-b6db-41f5-bac0-0d0b08afbda1)

**Comment by Chishikii** [comment]
Can you provide me with some steps to reproduce the issue as I am having trouble getting it.

**Comment by XtroTheArctic** [comment]
Phew. I was able to repro it in your project. I wasn't hopeful but it was relatively easy to repro.

![image](https://github.com/Chishikii/URP-Render-Features/assets/6631429/8e7aeab6-4dee-4b80-8a80-d91f4eab5f22)

[URP-Render-Features.zip](https://github.com/Chishikii/URP-Render-Features/files/14016053/URP-Render-Features.zip)

**Comment by Chishikii** [comment]
I fixed your issue here 6de2b5da4fe30c3c1935c001bc822818ec67ffde. 

I also fixed the depth sampling / writing to be working correctly now. As far as I understand it there is no issue using it.
